import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Profile from "@/components/Profile";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Sameer's Blog",
  description: "Generated by Sameer Jha",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} dark:bg-sky-900`}>
        <Navbar />
        <Profile />
        {children}
      </body>
    </html>
  );
}
